apiVersion: batch/v1
kind: CronJob
metadata:
  name: tenant-cleaner
  namespace: webhook-receiver
  labels:
    app.kubernetes.io/name: tenant-cleaner  
spec:
  schedule: "55 21 * * *" # run daily 5 min before maintenance
  timeZone: Pacific/Auckland
  concurrencyPolicy: Forbid # no more than one instance
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: tenant-cleaner
        spec:
          restartPolicy: Never
          serviceAccountName: tenant-cleaner
          containers:
          - name: "tenant-cleaner"
            command: [ "/tenant-cleaner.sh" ]
            image: ghcr.io/elfhosted/webhook-receiver:2.8.2@sha256:f6569169f8ed427226cd756b264fedaf24992b9d23390610b275b290f332b066
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              privileged: false
              seccompProfile:
                type: RuntimeDefault   
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              capabilities:
                drop:
                - ALL              
            envFrom:
            - secretRef:
                name: webhook-receiver                  
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: "/tenant-cleaner.sh"
              subPath: tenant-cleaner.sh
              name: tenant-cleaner
          volumes:
            - name: tmp
              emptyDir: {}   
            - name: tenant-cleaner
              configMap:
                name: tenant-cleaner 
                defaultMode: 0755       